// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: test.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GetUserInfo_Get_FullMethodName = "/GetUserInfo/Get"
)

// GetUserInfoClient is the client API for GetUserInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetUserInfoClient interface {
	Get(ctx context.Context, in *Userinfo, opts ...grpc.CallOption) (*Reply, error)
}

type getUserInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUserInfoClient(cc grpc.ClientConnInterface) GetUserInfoClient {
	return &getUserInfoClient{cc}
}

func (c *getUserInfoClient) Get(ctx context.Context, in *Userinfo, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, GetUserInfo_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserInfoServer is the server API for GetUserInfo service.
// All implementations must embed UnimplementedGetUserInfoServer
// for forward compatibility
type GetUserInfoServer interface {
	Get(context.Context, *Userinfo) (*Reply, error)
	mustEmbedUnimplementedGetUserInfoServer()
}

// UnimplementedGetUserInfoServer must be embedded to have forward compatible implementations.
type UnimplementedGetUserInfoServer struct {
}

func (UnimplementedGetUserInfoServer) Get(context.Context, *Userinfo) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetUserInfoServer) mustEmbedUnimplementedGetUserInfoServer() {}

// UnsafeGetUserInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetUserInfoServer will
// result in compilation errors.
type UnsafeGetUserInfoServer interface {
	mustEmbedUnimplementedGetUserInfoServer()
}

func RegisterGetUserInfoServer(s grpc.ServiceRegistrar, srv GetUserInfoServer) {
	s.RegisterService(&GetUserInfo_ServiceDesc, srv)
}

func _GetUserInfo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Userinfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserInfoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetUserInfo_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserInfoServer).Get(ctx, req.(*Userinfo))
	}
	return interceptor(ctx, in, info, handler)
}

// GetUserInfo_ServiceDesc is the grpc.ServiceDesc for GetUserInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetUserInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetUserInfo",
	HandlerType: (*GetUserInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GetUserInfo_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
